version: "3"
services:

  master:
    container_name: master
    image: van15h/master:v1
    ports:
      - "5000:8080"
    networks:
      - cloud_storage
    environment:
      - NODE1=node1
      - NODE2=node2
      - NODE3=node3
      - NODE4=node4

  node1:
    container_name: node1
    image: van15h/slave:v1
    ports:
      - "5001:8080"
    volumes:
      - ./data/node1:/myapp/data
    networks:
      - cloud_storage

  node2:
    container_name: node2
    image: van15h/slave:v1
    ports:
      - "5002:8080"
    volumes:
      - ./data/node2:/myapp/data
    networks:
      - cloud_storage

  node3:
    container_name: node3
    image: van15h/slave:v1
    ports:
      - "5003:8080"
    volumes:
      - ./data/node3:/myapp/data
    networks:
      - cloud_storage

  node4:
    container_name: node4
    image: van15h/slave:v1
    ports:
      - "5004:8080"
    volumes:
      - ./data/node4:/myapp/data
    networks:
      - cloud_storage

networks:
  cloud_storage: